spec:
  name: hyperliquid-liq
  workers:
    - name: liq-worker
      environment_slug: python
      instance_size_slug: basic-xxs
      instance_count: 1
      git:
        branch: main
        repo_clone_url: https://github.com/Davidyu1024/btc-dashboard.git
      build_command: pip install -r requirements.txt
      run_command: python scripts/hyperliquid_liq_collector.py
      envs:
        - key: HYPEDEXER_API_KEY
          scope: RUN_TIME
          type: SECRET
          value: ${HYPEDEXER_API_KEY}
